"""MedNexus_Intelligence — report routes. Copyright © 2026 Ayush Anand. All rights reserved."""

from fastapi import APIRouter, HTTPException, Response

from services.ai_service import AIServiceError, download_report_pdf, generate_report

router = APIRouter()


@router.get("/report")
async def get_report(file_id: str):
    """
    Retrieve generated report data.
    
    DEPRECATED: This endpoint is for legacy compatibility.
    Use POST /api/process instead to get the full report as JSON.
    
    - Accepts file_id as query parameter
    - Returns structured report data
    - This endpoint returns JSON only (no PDF rendering)
    """
    if not file_id:
        raise HTTPException(
            status_code=400,
            detail="file_id query parameter is required"
        )
    
    try:
        report_data = await generate_report(file_id)
        
        return {
            "file_id": file_id,
            "report": report_data.model_dump()
        }
    except AIServiceError as e:
        raise HTTPException(status_code=e.status_code, detail=e.detail)
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to retrieve report: {str(e)}"
        )


@router.get("/report/pdf")
async def get_report_pdf(file_id: str, inline: bool = False):
    """Download template-based PDF generated by pipeline service.

    This endpoint returns the PDF rendered by the pipeline backend using
    templates/report.html, instead of frontend html2pdf rendering.
    """
    if not file_id:
        raise HTTPException(
            status_code=400,
            detail="file_id query parameter is required"
        )

    try:
        pdf_bytes, filename = await download_report_pdf(file_id)
        disposition = "inline" if inline else "attachment"
        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={
                "Content-Disposition": f'{disposition}; filename="{filename}"',
                "Cache-Control": "no-store",
                "X-PDF-Source": "pipeline-template-report-html",
            },
        )
    except AIServiceError as e:
        raise HTTPException(status_code=e.status_code, detail=e.detail)
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to retrieve report PDF: {str(e)}"
        )
